# This is the configuration used to check the rubocop source code.
AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - lib/**/*
    - bin/*
  Exclude:
    - .rubocop.yml
inherit_from: rubocop-todo.yml
